// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/neo4j_query component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("neo4j_query")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/neo4jqueryreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
	LogsStability    = component.StabilityLevelDevelopment
)
