// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/attributecache component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("attributecache")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributecacheprocessor"
)

const (
	TracesStability   = component.StabilityLevelDevelopment
	MetricsStability  = component.StabilityLevelDevelopment
	LogsStability     = component.StabilityLevelDevelopment
	ProfilesStability = component.StabilityLevelDevelopment
)
