// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributecacheprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributecacheprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                     metric.Meter
	mu                                        sync.Mutex
	registrations                             []metric.Registration
	ProcessorAttributecacheItemsEnriched      metric.Int64Counter
	ProcessorAttributecacheItemsPassthrough   metric.Int64Counter
	ProcessorAttributecacheItemsProcessed     metric.Int64Counter
	ProcessorAttributecacheLookupDuration     metric.Float64Histogram
	ProcessorAttributecacheRefreshErrorsTotal metric.Int64Counter
	ProcessorAttributecacheRefreshTotal       metric.Int64Counter
	ProcessorAttributecacheTableRows          metric.Int64Gauge
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorAttributecacheItemsEnriched, err = builder.meter.Int64Counter(
		"otelcol_processor_attributecache_items_enriched",
		metric.WithDescription("Total telemetry items that matched a lookup row and were enriched. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorAttributecacheItemsPassthrough, err = builder.meter.Int64Counter(
		"otelcol_processor_attributecache_items_passthrough",
		metric.WithDescription("Total telemetry items that did not match the input filter and passed through unchanged. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorAttributecacheItemsProcessed, err = builder.meter.Int64Counter(
		"otelcol_processor_attributecache_items_processed",
		metric.WithDescription("Total telemetry items evaluated against the input filter. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorAttributecacheLookupDuration, err = builder.meter.Float64Histogram(
		"otelcol_processor_attributecache_lookup_duration",
		metric.WithDescription("Latency histogram of lookup table match operations. [Development]"),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries([]float64{1e-05, 0.0001, 0.001, 0.01, 0.1}...),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorAttributecacheRefreshErrorsTotal, err = builder.meter.Int64Counter(
		"otelcol_processor_attributecache_refresh_errors_total",
		metric.WithDescription("Total number of failed table refresh attempts. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorAttributecacheRefreshTotal, err = builder.meter.Int64Counter(
		"otelcol_processor_attributecache_refresh_total",
		metric.WithDescription("Total number of successful table refreshes. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorAttributecacheTableRows, err = builder.meter.Int64Gauge(
		"otelcol_processor_attributecache_table_rows",
		metric.WithDescription("Current number of rows loaded in the lookup table. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
